# Backbone
backbone: resnet50

# Transfer loss related
transfer_loss_weight: 1
transfer_loss: djp_mmd

# Optimizer related
lr: 0.003
weight_decay: 5e-4
momentum: 0.9
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75

# Training related
n_iter_per_epoch: 100
n_epoch: 50

# Others
seed: 1
num_workers: 3
